pages:
  - song_name: Anisuthide
    message: The beginning notes of this songs reminds me so much how we learnt it together
    lyrics: {lyrics}
    background_image: https://images.app.goo.gl/WGz6bcmVTcTnFLtZ9
  - song_name: Paravashanadenu
    message: This I just can't tell how much I 'm into it. Back in the days it was like when ever I think of you the radio was playing this song as a perfect BGM. I have got a very special relation ship with this song about you
    lyrics: {lyrics}
    background_image: /content/drive/My Drive/pikapika/storybooks/raw pics/sd3s/generated_3576770096.jpeg.jpg
  - song_name: Thoogu manchadalli
    message: This song has been like a default song for us through out when ever we slept. An extreamly exquisite song and wherever or when ever i hear this song, it puts me into a different mood altogether. The lyrics are for you...
    lyrics: {lyrics}
    background_image: /content/drive/My Drive/pikapika/storybooks/raw pics/sd3s/generated_849887211.jpeg.jpg
  - song_name: gundelona
    message: You once recorded this song for me by singing it through out. I have listened to this so many times on my way to home and office.your recording was very much close to the original and was excellent.
    lyrics: {lyrics}
    background_image: /content/drive/My Drive/pikapika/storybooks/raw pics/sd3s/generated_280882741.jpeg.jpg
  - song_name: Adiga
    message: This entire movie songs for some reason felt like magic recreated for us. I love it especially because you see me in the movie. and these lyrics exactly converys my feeling for you at this very moment of our life. I love you and will take care of all of us.I love you moreee...
    lyrics: {lyrics}
    background_image: 